title: Young DevOps Notes
author: ranebull
email: ranebull@yandex.ru
description: > # this means to ignore newlines until "baseurl:"
  News about system administation, devops and security.
# social links
twitter_username: your-twitter-handle
github_username:  ranebull

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
logo: /assets/img/logo.jpeg
